# Docker Compose description of the combined application.
#
# 'docker-compose up' will run this.
version: '3'  # requires Docker Compose 1.13 or later

# This section describes the various containers (services).
services:
  web:
    container_name: API
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4015:4015
    command: python /main.py